In [117]:
import numpy as np
import matplotlib.pyplot as plt

In [118]:
x1 = np.array([0.5,1,1.5,1.1,1.9,2.2,2.6,2,2.5,3.1])
x2 = np.array([0.7,1.1,1.6,0.9,2.2,2.9,2.7,1.6,2.4,3])
print("Ori Feature Vectors:")
print(np.array([x1,x2]).T)

Ori Feature Vectors:
[[0.5 0.7]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]
 [1.9 2.2]
 [2.2 2.9]
 [2.6 2.7]
 [2.  1.6]
 [2.5 2.4]
 [3.1 3. ]]


In [119]:
# normalize the data
x1 = (x1 - np.mean(x1, axis=0))/np.std(x1)
x2 = (x2 - np.mean(x2, axis=0))/np.std(x2)

In [120]:
# combine to 2d matrix of dimension 10x2
X = np.vstack((x1, x2)).T
print("Normalized Feature Vectors:")
print(X)
# calculate the covariance matrix
cov_mat = np.cov(X, rowvar = False )


Normalized Feature Vectors:
[[-1.740994   -1.506743  ]
 [-1.09136937 -1.00864614]
 [-0.44174475 -0.38602507]
 [-0.96144445 -1.25769457]
 [ 0.07795496  0.36112022]
 [ 0.46772973  1.23278973]
 [ 0.98742943  0.9837413 ]
 [ 0.20787988 -0.38602507]
 [ 0.85750451  0.61016865]
 [ 1.63705406  1.35731394]]


In [107]:
# compute Eigenvalues and Eigenvectors
U, S, V = np.linalg.svd(cov_mat)
print("Eigenvectors:")
print(U)

Eigenvectors:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [108]:
# keeping both eigenvectors
n_comp = 2
U_reduced = U[:, :n_comp]

In [109]:
# examine dimension
print(U_reduced.shape)
print(X.shape)
print("Chosen eigenvector(s):")
print(U_reduced)
# Transform the data 
fin_data_all = np.dot(U_reduced.transpose(),X.transpose()).transpose()

(2, 2)
(10, 2)
Chosen eigenvector(s):
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [110]:
# keeping first eigenvectors
n_comp = 1
U_reduced = U[:, 0:n_comp]

In [111]:
# examine dimension
print(U_reduced.shape)
print(X.shape)
print("Chosen eigenvector(s):")
print(U_reduced)
# Transform the data 
fin_data_first = np.dot(U_reduced.transpose(),X.transpose()).transpose()

(2, 1)
(10, 2)
Chosen eigenvector(s):
[[-0.70710678]
 [-0.70710678]]


In [112]:
# feature vectors with both eigenvectors
print("Transformed Normalized Feature Vector - All components")
print(fin_data_all)

Transformed Normalized Feature Vector - All components
[[ 2.29649685  0.16564047]
 [ 1.48493521  0.05849416]
 [ 0.58532165  0.03939976]
 [ 1.56916825 -0.20948047]
 [-0.31047304  0.20022808]
 [-1.20244884  0.54097911]
 [-1.39382819 -0.0026079 ]
 [ 0.12596767 -0.41995421]
 [-1.03780164 -0.17489286]
 [-2.11733792 -0.19780613]]


In [113]:
# feature vectors with first eigenvector
print("Transformed Normalized Feature Vector - 1st component")
print(fin_data_first)

Transformed Normalized Feature Vector - 1st component
[[ 2.29649685]
 [ 1.48493521]
 [ 0.58532165]
 [ 1.56916825]
 [-0.31047304]
 [-1.20244884]
 [-1.39382819]
 [ 0.12596767]
 [-1.03780164]
 [-2.11733792]]
